server.port: 8083

spring.jackson:
  date-format: yyyy-MM-dd

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka

rss:
  base.url: http://www.ehfg.org/feed/
  sufix: 2016.rss