maintenance:
  user: patrick
  password: 123


server.port: 8080

eureka:
  dashboard.path: eureka-dasbhoard
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 30

spring.thymeleaf:
  cache: false
  excludedViewNames: tweetExport

# use this setting so the eureka dashboard will work with windows machine
spring:
  freemarker:
    prefer-file-system-access: false
