maintenance:
  user: patrick
  password: 123


server.port: 8080

eureka:
  dashboard.path: eureka-dashboard
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 30

spring.thymeleaf:
  cache: false
  excludedViewNames: tweetExport

# use this setting so the eureka dashboard will work with windows machine
spring:
  freemarker:
    prefer-file-system-access: false

zuul:
  prefix: /rest
  routes:
    sessions:
      serviceId: ehfgapp-program
      route: /sessions
      strip-prefix: false
    speakers:
      serviceId: ehfgapp-program
      route: /speakers
      strip-prefix: false
    internal:
      path: /**
      url: forward:/api
